#!/bin/sh
# Since Sublime is fucking insane and can't handle symlinks for the User
# directory, we'll need to manually copy stuff over.

# rm -rf $ZSHELL/sublime2/User
# cp -R ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User $ZSHELL/sublime3/User
