#!/bin/sh
# Setup a machine for Sublime Text 2
set -x

# symlink settings in
sublime_dir=~/Library/Application\ Support/Sublime\ Text\ 3/Packages
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -s "$ZSHELL/sublime3/User" "$sublime_dir"

# Grab the themes
cd "$sublime_dir"
git clone https://github.com/Yabatadesign/afterglow-theme/ "Theme - Afterglow"
git clone git://github.com/thinkpixellab/flatland.git "Theme - Flatland"
